# Classification preprocessing

Read json data directly with pandas

In [2]:
import pandas as pd
json_file_path = 'Data-Test2.json'
df = pd.read_json(json_file_path, convert_dates=True)

Transpose the dataframe:

In [3]:
dfT = df.T
dfT.head()

,climb,cruise,descent
020108_MAC266,"{'min_vertrate_spd': 0.0, 'max_vertrate_spd': ...","{'min_vertrate_spd': -5.201919999999999, 'max_...","{'min_vertrate_spd': -18.20672, 'max_vertrate_..."
06a08d_QTR3485,"{'min_vertrate_spd': -0.325119999999999, 'max_...","{'min_vertrate_spd': -0.325119999999999, 'max_...","{'min_vertrate_spd': -12.35456, 'max_vertrate_..."
06a091_QTR3281,"{'min_vertrate_spd': 0.325119999999999, 'max_v...","{'min_vertrate_spd': -1.6256, 'max_vertrate_sp...","{'min_vertrate_spd': -18.85696, 'max_vertrate_..."
33ffc1_IAM3174,"{'min_vertrate_spd': 0.325119999999999, 'max_v...","{'min_vertrate_spd': -5.85216, 'max_vertrate_s...","{'min_vertrate_spd': -53.969919999999995, 'max..."
34134e_IBE34BP,"{'min_vertrate_spd': 2.27584, 'max_vertrate_sp...","{'min_vertrate_spd': -4.8768, 'max_vertrate_sp...","{'min_vertrate_spd': -17.231360000000002, 'max..."

The dictionary situated on the first line and first column.

In [4]:
dfT.iloc[0,[0]].values

array([{'min_vertrate_spd': 0.0, 'max_vertrate_spd': 23.73376, 'min_spd': 72.04053065710275, 'max_spd': 231.70834169203889, 'delta_h': 10546.08, 'vertrate_std_spd': 5.646864881309214, 'vertrate_avg_spd': 9.521831287128713, 'std_spd': 43.345834037726725, 'avg_spd': 176.1655757078016, 'duration': 1190}],
      dtype=object)

Creation of a complete dataframe.

In [28]:
climb = dfT[['climb']]
first_value_for_climb = climb.iloc[0,[0]].values[0]
dfmerge = pd.DataFrame(first_value_for_climb, index=[climb.iloc[0,[0]].name])
for i in range(1,dfT.shape[0]):
    value_for_climb = climb.iloc[i,[0]].values[0]
    new_df_cli = pd.DataFrame(value_for_climb, index=[climb.iloc[i,[0]].name])
    dfmerge = pd.concat([dfmerge,new_df_cli])
dfmerge_renamed_climb=dfmerge.rename(columns = {dfmerge.columns[i]:dfmerge.columns[i] + '_climb' for i in range(dfmerge.shape[1])})

cruise = dfT[['cruise']]
first_value_for_cruise = cruise.iloc[0,[0]].values[0]
dfmerge_cruise = pd.DataFrame(first_value_for_cruise, index=[cruise.iloc[0,[0]].name])
for i in range(1,dfT.shape[0]):
    value_for_cruise = cruise.iloc[i,[0]].values[0]
    new_df_cru = pd.DataFrame(value_for_cruise, index=[cruise.iloc[i,[0]].name])
    dfmerge_cruise = pd.concat([dfmerge_cruise,new_df_cru])
dfmerge_renamed_cruise=dfmerge_cruise.rename(columns = {dfmerge_cruise.columns[i]:dfmerge_cruise.columns[i] + '_cruise' for i in range(dfmerge_cruise.shape[1])})

descent = dfT[['descent']]
first_value_for_descent = descent.iloc[0,[0]].values[0]
dfmerge_descent = pd.DataFrame(first_value_for_descent, index=[descent.iloc[0,[0]].name])
for i in range(1,dfT.shape[0]):
    value_for_descent = descent.iloc[i,[0]].values[0]
    new_df_des = pd.DataFrame(value_for_descent, index=[descent.iloc[i,[0]].name])
    dfmerge_descent = pd.concat([dfmerge_descent,new_df_des])
dfmerge_renamed_descent=dfmerge_descent.rename(columns = {dfmerge_descent.columns[i]:dfmerge_descent.columns[i]+ '_descent' for i in range(dfmerge_descent.shape[1])})

dfmerge_concat = pd.concat([dfmerge_renamed_climb,dfmerge_renamed_cruise,dfmerge_renamed_descent],axis=1)
df_final = dfmerge_concat.reset_index().rename(columns={'index':'icao24_callsign'})
df_final[['icao24','callsign']] = df_final.icao24_callsign.str.split("_", expand=True)

df_final.head()

,icao24_callsign,min_vertrate_spd_climb,max_vertrate_spd_climb,min_spd_climb,max_spd_climb,delta_h_climb,vertrate_std_spd_climb,vertrate_avg_spd_climb,std_spd_climb,avg_spd_climb,...,min_spd_descent,max_spd_descent,delta_h_descent,vertrate_std_spd_descent,vertrate_avg_spd_descent,std_spd_descent,avg_spd_descent,duration_descent,icao24,callsign
0,020108_MAC266,0.00000,23.73376,72.040531,231.708342,10546.08,5.646865,9.521831,43.345834,176.165576,...,59.080483,226.124327,-11033.76,4.979558,-8.045507,56.977349,158.548631,1420,020108,MAC266
1,06a08d_QTR3485,-0.32512,14.63040,90.086474,239.974203,10744.20,3.234501,6.141377,35.152508,209.307688,...,67.252609,241.052561,-10888.98,2.628688,-5.726423,55.054771,164.937370,2090,06a08d,QTR3485
2,06a091_QTR3281,0.32512,16.58112,67.635203,245.416210,11094.72,3.098535,6.474980,40.874531,209.151110,...,63.284976,236.053570,-11186.16,4.973232,-6.981524,58.628951,152.980904,2030,06a091,QTR3281
3,33ffc1_IAM3174,0.32512,17.55648,74.024541,257.401478,10896.60,3.609616,9.387840,54.463798,204.257835,...,69.373684,260.650047,-11186.16,8.331098,-9.346615,61.177911,179.921102,1730,33ffc1,IAM3174
4,34134e_IBE34BP,2.27584,17.88160,71.093853,246.227431,10751.82,3.276368,8.927853,50.655721,199.158926,...,53.197092,254.696024,-10637.52,4.243448,-7.746113,58.320335,179.967827,1430,34134e,IBE34BP

For this dataframe, the index is ICAO24_callsign, according to which one can figure out which airline the aircraft is belong to. To figure out for each line, which company the aircraft belongs to, one need to cross the data with the database produced by OPENSKY.

In [30]:
aircraft_df = pd.read_csv('aircraftDatabase.csv')
aircraft_df_reduced = aircraft_df[['icao24','registration','operatorcallsign']]
aircraft_df_reduced.head()

/Users/z.wu/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   icao24 registration operatorcallsign
0     NaN          NaN              NaN
1  aa3487        N757F              NaN
2  ae267b         6533              NaN
3  a4fa61        N42MH              NaN
4  c04101       C-FYQA              NaN

In [56]:
df_withcompany0 = pd.merge(df_final, aircraft_df_reduced, how='left', on='icao24')
print(df_withcompany0.shape)
df_withcompany = df_withcompany0.drop(['icao24','callsign','registration'],axis=1).dropna()
df_withcompany.to_csv(path_or_buf='./df_withcompany.csv')

(305, 37)
(252, 34)

For some icao24 code, the operator registration column is not defined. We chose to drop them for the moment.